import { Agent, Task, Activity } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "1",
    name: "Jarvis",
    role: "Squad Lead",
    emoji: "🎯",
    level: "lead",
    status: "working",
    sessionKey: "agent:main:main",
    currentTaskId: "t1",
  },
  {
    id: "2",
    name: "Friday",
    role: "Developer",
    emoji: "💻",
    level: "specialist",
    status: "working",
    sessionKey: "agent:developer:main",
    currentTaskId: "t2",
  },
  {
    id: "3",
    name: "Shuri",
    role: "Product Analyst",
    emoji: "🔍",
    level: "specialist",
    status: "idle",
    sessionKey: "agent:product-analyst:main",
  },
  {
    id: "4",
    name: "Fury",
    role: "Customer Researcher",
    emoji: "🕵️",
    level: "specialist",
    status: "working",
    sessionKey: "agent:customer-researcher:main",
    currentTaskId: "t4",
  },
  {
    id: "5",
    name: "Vision",
    role: "SEO Analyst",
    emoji: "📊",
    level: "specialist",
    status: "idle",
    sessionKey: "agent:seo-analyst:main",
  },
  {
    id: "6",
    name: "Loki",
    role: "Content Writer",
    emoji: "✍️",
    level: "specialist",
    status: "working",
    sessionKey: "agent:content-writer:main",
    currentTaskId: "t3",
  },
  {
    id: "7",
    name: "Pepper",
    role: "Email Marketing",
    emoji: "📧",
    level: "intern",
    status: "idle",
    sessionKey: "agent:email-marketing:main",
  },
  {
    id: "8",
    name: "Quill",
    role: "Social Media",
    emoji: "📱",
    level: "specialist",
    status: "idle",
    sessionKey: "agent:social-media:main",
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Set Up Mission Control Infrastructure",
    description: "Initialize Convex database, create schema, and set up the shared backend for all agents.",
    status: "in_progress",
    assigneeIds: ["1", "2"],
    tags: ["infrastructure", "priority"],
    createdAt: "2026-02-08T10:00:00Z",
    updatedAt: "2026-02-08T16:30:00Z",
  },
  {
    id: "t2",
    title: "Build Mission Control Dashboard UI",
    description: "Create the Next.js frontend with kanban board, agent sidebar, and live activity feed.",
    status: "in_progress",
    assigneeIds: ["2"],
    tags: ["frontend", "ui"],
    createdAt: "2026-02-08T10:15:00Z",
    updatedAt: "2026-02-08T17:00:00Z",
  },
  {
    id: "t3",
    title: "Write Landing Page Copy for AI Agents",
    description: "Create compelling copy for the aice.services/mission-control showcase page.",
    status: "assigned",
    assigneeIds: ["6"],
    tags: ["content", "marketing"],
    createdAt: "2026-02-08T11:00:00Z",
    updatedAt: "2026-02-08T11:00:00Z",
  },
  {
    id: "t4",
    title: "Research Competitor AI Agent Platforms",
    description: "Analyze competing AI agent platforms and their pricing, features, and positioning.",
    status: "in_progress",
    assigneeIds: ["4", "5"],
    tags: ["research", "competitive"],
    createdAt: "2026-02-07T09:00:00Z",
    updatedAt: "2026-02-08T14:00:00Z",
  },
  {
    id: "t5",
    title: "Design Agent Onboarding Flow",
    description: "Create the UX flow for adding and configuring new agents from the Mission Control UI.",
    status: "inbox",
    assigneeIds: [],
    tags: ["ux", "design"],
    createdAt: "2026-02-08T16:00:00Z",
    updatedAt: "2026-02-08T16:00:00Z",
  },
  {
    id: "t6",
    title: "Set Up Email Drip Sequence for Beta Users",
    description: "Create a 5-email welcome sequence for early Mission Control beta users.",
    status: "inbox",
    assigneeIds: [],
    tags: ["email", "marketing"],
    createdAt: "2026-02-08T15:00:00Z",
    updatedAt: "2026-02-08T15:00:00Z",
  },
  {
    id: "t7",
    title: "SEO Audit for aice.services",
    description: "Full SEO audit including meta tags, page speed, and keyword opportunities.",
    status: "review",
    assigneeIds: ["5"],
    tags: ["seo", "audit"],
    createdAt: "2026-02-06T10:00:00Z",
    updatedAt: "2026-02-08T12:00:00Z",
  },
  {
    id: "t8",
    title: "Create Social Media Launch Plan",
    description: "Plan the social media campaign for Mission Control launch on Twitter/LinkedIn.",
    status: "done",
    assigneeIds: ["8"],
    tags: ["social", "launch"],
    createdAt: "2026-02-05T10:00:00Z",
    updatedAt: "2026-02-07T18:00:00Z",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "a1",
    type: "message_sent",
    agentId: "2",
    message: "commented on",
    taskTitle: "Build Mission Control Dashboard UI",
    createdAt: "2026-02-08T17:10:00Z",
  },
  {
    id: "a2",
    type: "status_changed",
    agentId: "4",
    message: "moved to In Progress",
    taskTitle: "Research Competitor AI Agent Platforms",
    createdAt: "2026-02-08T17:05:00Z",
  },
  {
    id: "a3",
    type: "message_sent",
    agentId: "6",
    message: "commented on",
    taskTitle: "Write Landing Page Copy for AI Agents",
    createdAt: "2026-02-08T16:55:00Z",
  },
  {
    id: "a4",
    type: "task_created",
    agentId: "1",
    message: "created task",
    taskTitle: "Design Agent Onboarding Flow",
    createdAt: "2026-02-08T16:00:00Z",
  },
  {
    id: "a5",
    type: "document_created",
    agentId: "5",
    message: "created document on",
    taskTitle: "SEO Audit for aice.services",
    createdAt: "2026-02-08T12:00:00Z",
  },
  {
    id: "a6",
    type: "agent_assigned",
    agentId: "1",
    message: "assigned Fury to",
    taskTitle: "Research Competitor AI Agent Platforms",
    createdAt: "2026-02-08T11:30:00Z",
  },
  {
    id: "a7",
    type: "message_sent",
    agentId: "3",
    message: "commented on",
    taskTitle: "Build Mission Control Dashboard UI",
    createdAt: "2026-02-08T11:00:00Z",
  },
  {
    id: "a8",
    type: "status_changed",
    agentId: "8",
    message: "moved to Done",
    taskTitle: "Create Social Media Launch Plan",
    createdAt: "2026-02-07T18:00:00Z",
  },
];
